# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Characters"

on:  # yamllint disable-line rule:truthy
    push:
        branches:
        - "master"
    pull_request: null
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    spelling:
        name: "Spelling"
        runs-on: "ubuntu-24.04"
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
        -
            name: "Search for misspellings"
            uses: "crate-ci/typos@master"

    editorconfig:
        name: "EditorConfig"
        runs-on: "ubuntu-24.04"
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
        -
            name: "Check EditorConfig configuration"
            run: "test -f .editorconfig"
        -
            name: "Check adherence to EditorConfig"
            uses: "greut/eclint-action@v0"
